sudo: false
language: python
python:
  - "3.4"

cache: false

install:
  - pip install coveralls
  - pip install -e .

addons:
  sonarcloud:
    organization: "gale-partners"
    token:
      secure: $SONAR_TOKEN
    brances:
      - master

script:
  - coverage run `which django-admin.py` test
  - if [ "$TRAVIS_BRANCH" = "master" ]; then sonar-scanner; fi

notifications:
  email: false

after_success:
  - coveralls
