sudo: false
language: python
python:
  - "3.4"

cache: false

install:
  - pip install coveralls
  - pip install -e .

addons:
  sonarcloud:
    organization: "gale-partners"
    token:
      secure: $SONAR_TOKEN
    github_token:
      secure: $GITHUB_TOKEN

script:
  - coverage run `which django-admin.py` test
  - sonar-scanner

notifications:
  email: false

after_success:
  - coveralls
